version: 2.1

jobs:

  TWRP-holi-:

   docker:

      - image: caliberrr/docker-image:Twrp-build

   steps:

      - run:

          name: Syncing source

          no_output_timeout: 20m

          command: |

            cd ~

            mkdir work && cd work

            repo init --depth=1 -u https://github.com/Ranjith0o7/platform_manifest_twrp_aosp -b twrp-12.1

            repo sync  --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune -j$(nproc --all)

            mkdir -p device/xiaomi && cd device/xiaomi

            git clone https://github.com/Spector0/device_qualcomm_holi-twrp device/qualcomm/holi

      - run:

          name: Building

          no_output_timeout: 20m

          command: |

            cd ~

            cd ~/work

            . build/envsetup.sh &&lunch twrp_$DEVICE-eng &&export ALLOW_MISSING_DEPENDENCIES=true && mka bootimage

             

      - run:

          name: Send To Telegram

          no_output_timeout: 20m

          command: |

            cd ~/work/out/target/product/holi

            ZIPNAME="TWRP-$(date +%d_%m_%Y_%H_%M)-holi.zip"

            sudo zip -r9 $ZIPNAME boot.img

            curl -F chat_id=642572823 -F document=@$ZIPNAME -F parse_mode=markdown https://api.telegram.org/bot5385860828:AAGPiG6cAYS-3u_bFQNkyZDzJKeP_P3__Zo/sendDocument

            

            

workflows:

  version: 2.1

  cooking:

    jobs:

      - TWRP-holi